### ISSUE TITLE
Should use length of byte buffer, not string

### ISSUE THREAD

**Issue by cuiliang** [ba32107/dotnet-chrome-native-messaging#7]
https://github.com/ba32107/dotnet-chrome-native-messaging/blob/d290ffc2070a26839b2cbe4e156ecca5d64b0b9a/Chrome.NativeMessaging/Chrome.NativeMessaging/NativeMessagingHost.cs#L128

Hi, thanks for you code. 
There is a problem in this line, If the string to send contains non-ascii character, the  string length value will mismatch buffer length.

**Comment by ba32107** [comment]
Hi @cuiliang, thanks, I will look into it as soon as I can.

**Comment by ba32107** [comment]
Hi @cuiliang, this has been fixed, I just pushed the new package (https://www.nuget.org/packages/Chrome.NativeMessaging/1.0.33). It is currently validating, it should be available shortly.

Thanks for raising this bug!
